### ISSUE TITLE
Support configuration of sslcontext

### ISSUE THREAD

**Issue by sdmoralesma** [babashka/http-client#22]
**Is your feature request related to a problem? Please describe.**
Allow simple configuration of the `sslcontext` similar to hato's: https://github.com/gnarroway/hato/blob/7862f9e3ab692ea499b935842978688831e61bfd/src/hato/client.clj#L91.

Otherwise, I would have to configure the script with system properties or use interop code.

**Additional context**
Chat in slack: https://clojurians.slack.com/archives/C04J0N76E2G/p1679865379426629

**Comment by borkdude** [comment]
@sdmoralesma Can you describe how you would like the API to look like, roughly?
