### ISSUE TITLE
Add support for proxy authentication 

### ISSUE THREAD

**Issue by amithgeorge** [babashka/http-client#28]
We use Heroku's Fixie proxy. That requires a username and password to be provided for the proxy, else all requests return a 407 HTTP status code. 

As per the [Java docs](https://docs.oracle.com/en/java/javase/17/docs/api/java.net.http/java/net/http/HttpClient.html), we are supposed to set an Authenticator to allow for proxy authentication. 

Please enable support for specifying the proxy username and password when building the client.

**Comment by amithgeorge** [comment]
I haven't tried this out yet. Will do so in a bit. Reading the [code](https://github.com/babashka/http-client/blob/17af6c41ef61d18acce281048f9a5fc3291004f0/src/babashka/http_client/internal.clj#LL107C46-L107C46), only the host and port are read from the proxy option.

**Comment by borkdude** [comment]
Ah sorry, I missed that. Can you try 0.3.11 which now has an `:authenticator` option to which you can pass `:user` and `:pass`.
