### ISSUE TITLE
Throwing on exceptional status with async mode, wraps response in an additional future

### ISSUE THREAD

**Issue by axvr** [babashka/http-client#38]
I assume this is unintentional behaviour (at least it caught me by surprise).

```clojure
;; ------
;; Non-exceptional status code:

@(http/get "https://httpbin.org/status/200" {:async true})
;; => {:status 200, ...}

;; -------
;; Exceptional status code:

@(http/get "https://httpbin.org/status/422" {:async true})
;; => #object[jdk.internal.net.http.common.MinimalFuture ...]

@@(http/get "https://httpbin.org/status/422" {:async true})
;; => Exception
```

Using bb.http-client v0.4.12 on JVM 20.0.2.

**Comment by borkdude** [comment]
Thanks for the report. This seems unintentional indeed! I hope to have some time to look into a fix soon, but feel free to look into it as well, if you want.

**Comment by axvr** [comment]
Thanks.  I'll try to look into it myself too.  Will let you know if I find anything.
