### ISSUE TITLE
Response header map includes `":status"`

### ISSUE THREAD

**Issue by axvr** [babashka/http-client#39]
This looked like a bug so thought I'd raise it just in case.  In the response header map, note how it contains the key `":status"`, rather than `"status"`.

```clojure
(http/get "https://httpbin.org/status/200")
;; => {:status 200,
;;     :body "",
;;     :headers
       {":status" "200",
;;      "content-type" "text/html; charset=utf-8",
;;      ...},
;;     :request
;;     {:headers
;;      {:accept "*/*",
;;       :accept-encoding ["gzip" "deflate"],
;;       :user-agent "babashka.http-client/0.4.12"},
;;      :uri #object[java.net.URI 0x78b6147f "https://httpbin.org/status/200"],
;;      :method :get}}
```

**Comment by borkdude** [comment]
Looks like a bug indeed

**Comment by borkdude** [comment]
Nope, it seems to be coming from java.net.http itself:

https://github.com/AdoptOpenJDK/openjdk-jdk/blob/9d8ad2ed62325bd8d813974d5aa1e031ed8bf8da/src/java.net.http/share/classes/jdk/internal/net/http/hpack/SimpleHeaderTable.java#L55
