### ISSUE TITLE
final url when using {:follow-redirects :always} ?

### ISSUE THREAD

**Issue by matteoredaelli** [babashka/http-client#41]
Hello

Where could I find the final url when redirects occur?

(http/get "https://httpstat.us/302" {:client (http/client {:follow-redirects :always})})

:uri is the original url 

   :uri #object[java.net.URI 0x7a729f84 "https://httpstat.us/302"]

Using haop :uri contains teh final url

Thanks in advance
Matteo

**Comment by borkdude** [comment]
@matteoredaelli I don't know where you get the `:uri` value from. Can you give a more full repro where this is unambiguously clear?

**Comment by matteoredaelli** [comment]
With hato I get the final url in this way

```
user=> (require '[hato.client :as hc])
nil
user=> (:uri (hc/get "https://pirelli.com/"  {:http-client {:redirect-policy :always}}))
"https://www.pirelli.com/global/en-ww/homepage/"
```

With this library how could I get it?

```
user=> (require '[babashka.http-client :as http])
nil
user=> (:uri (http/get "https://pirelli.com/" {:client (http/client {:follow-redirects :always})}))
nil
```

Thanks in advance

**Comment by borkdude** [comment]
Fixed. Do you need a release?

**Comment by matteoredaelli** [comment]
no, thanks!

**Comment by borkdude** [comment]
Made one anyway: 0.4.14
