### ISSUE TITLE
Nicer docstrings and/or arglists

### ISSUE THREAD

**Issue by vemv** [babashka/http-client#51]
Hi @borkdude, 

thanks for the great lib.

A common gripe I have with clj http libs is that they don't have useful docstrings, normally they're detailed on one common defn but not in the other ones.

I'd love if the simplest thing was done, namely having nearly-identical documentation for `get`, `delete`, `patch` etc.

Is it something that could be added to `http-client`?

Cheers - V

**Comment by borkdude** [comment]
Sure, why not!

**Comment by borkdude** [comment]
No wait, those already have docstrings. I don't see the need to copy paste the entire docstring of `request` to `get` etc to be honest and then maintain changes all over the place.

**Comment by vemv** [comment]
I'd say it's the sort of thing that is painful for the maintainer once or a couple times and then benefits 1000 developers 100 times each.

Not like HTTP client APIs are expected to change a whole lot over the years :)

**Comment by borkdude** [comment]
The word "see " occurs 33 times in clojure core. E.g. 

``` clojure
(defn slurp
  "Opens a reader on f and reads all its contents, returning a string.
  See clojure.java.io/reader for a complete list of supported arguments."
  {:added "1.0"
   :tag String}
  ([f & opts]
     (let [opts (normalize-slurp-opts opts)
           sw (java.io.StringWriter.)]
       (with-open [^java.io.Reader r (apply jio/reader f opts)]
         (jio/copy r sw)
         (.toString sw)))))
```

I don't know about you, but I don't have trouble looking up the docs of functions/classes references in "See ..." ;-)
Sorry, not going to do this.

**Comment by vemv** [comment]
What if I did it? Seems a fairly short job.

Seeing and memorizing things seems a not-very-Clojurey thing to do when we have all these fantastic tools around.

**Comment by vemv** [comment]
Also, I recall from some good source that clojure.core docstrings are forcibly short for tech reasons related to bootstrapping, something like that.

**Comment by vemv** [comment]
> this is why we have references

What existing tool parses them?
