### ISSUE TITLE
Address failing test

### ISSUE THREAD

**Issue by lread** [babashka/http-client#61]
I see a test failing on CI:

```
FAIL in (post-test) (http_client_test.clj:137)
HttpRequest$BodyPublisher body
expected: (not (str/includes? (:body (http/post "https://postman-echo.com/post" {:body (io/input-stream "README.md")})) "content-length"))
  actual: (not (not true))
```

I'd like to fix this before making any other changes.
But I might need a hand in understanding the test itself.

**Comment by borkdude** [comment]
I'd assume the exact response changed due to changes in postman's endpoint. The test is just to see if a certain body type is accepted and sent correctly to the web server
