### ISSUE TITLE
Make default client accept gzip and deflate

### ISSUE THREAD

**Issue by borkdude** [babashka/http-client#7]
- Make default client accept gzip and deflate
- Expose `default-client-options` so they can be used in custom client creation

**Comment by lispyclouds** [comment]
Also adding a default `Accept: */*` would be good as some servers seem to depend on it.

**Comment by lispyclouds** [comment]
@borkdude if we add `Accept: */*` as a default, we dont need to add the gzip and deflate right? The decompress interceptors handle it anyways right?

**Comment by borkdude** [comment]
I think the acceptance of encodings is done like this:

```
(http/get "https://api.stackexchange.com/2.2/sites"
  {:headers {"Accept-Encoding" ["gzip" "deflate"]}})
```

**Comment by lispyclouds** [comment]
Ah okay, was confused with the `Accept` header. Will add these as well.

**Comment by lispyclouds** [comment]
For the `Accept` and `Accept-Encoding` headers, should the provided ones override the defaults or be merged? Since its a array that we need to send?

**Comment by borkdude** [comment]
How I would do it: for a custom client, it uses no options, but the default-client-options should also exposed, so you can pick / merge from those

**Comment by lispyclouds** [comment]
but when the user uses a default client, the opts provided by the user should be merged into the default-options and then sent? if yes, should it be a deep merge?

**Comment by borkdude** [comment]
Probably yes...

**Comment by lispyclouds** [comment]
The deep merge seems a bit non-trivial i think, have to deal with a value or a vec of values for these headers and the key could either be a keyword or a string. If you have a suggestion for an deep merge that could handle this, gladly accepted or was thinking to merge only the top level keys. i.e. if the `:headers` is provided, we would merge the maps from the provided one into the default one and not the value of each of the headers too. Thoughts?

**Comment by lispyclouds** [comment]
`Accept` and `Accept-Encoding` from the provided map would take preference.

**Comment by lispyclouds** [comment]
curl seems to behave like that:
```sh
$ curl https://httpbin.org/get
{
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.85.0",
    "X-Amzn-Trace-Id": "Root=1-63b9a195-1ee2bec474f1555f3bbf0615"
  },
  "origin": "188.214.11.166",
  "url": "https://httpbin.org/get"
}

$ curl -H "accept:foo" https://httpbin.org/get
{
  "args": {},
  "headers": {
    "Accept": "foo",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.85.0",
    "X-Amzn-Trace-Id": "Root=1-63b9a1ab-42465b72355fe29626716a5d"
  },
  "origin": "188.214.11.166",
  "url": "https://httpbin.org/get"
}
```

**Comment by borkdude** [comment]
Fixed on main branch
